heat_template_version: "2018-08-31"
description: "create template to automation project configuration and start services automatically"

parameters:
  image_id:
    type: string
    description: base image name
    default: "Ubuntu-20.04"
  app-flavor-name:
    type: string
    description: flavor name or id for apps
    default: "Custom_falvor1"
  db-flavor-name:
    type: string
    description: flavor name or id for mongodb
    default: "Custom_falvor2"

resources:
  network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: auth-app
  network_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      cidr: "192.168.65.0/26"
      dns_nameservers: ["8.8.8.8"]
      gateway_ip: "192.168.65.1"
      ip_version: 4
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }
      name: cloud-app
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: network_subnet }
  port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network }
      fixed_ips:
        - subnet_id: { get_resource: network_subnet }
  port2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network }
      fixed_ips:
        - subnet_id: { get_resource: network_subnet }
  instance1:
    type: OS::Nova::Server
    properties:
      name: instance1
      image: { get_param: image_id }
      flavor: Custom_falvor1
      networks:
        - port: { get_resource: port1}   
        
  instance2:
    type: OS::Nova::Server
    properties:
      name: instance2
      image: { get_param: image_id }
      flavor: Custom_falvor1
      networks:
        - port: { get_resource: port2}      
        
        
  security_group_mongodb:
    type: OS::Neutron::SecurityGroup
    properties:
      description: 'related to mongodb,for port 27017,SSH,HTTP'
      name: security-group-mongodb
      rules:
      - direction: egress
        ethertype: IPv4
        remote_ip_prefix: 0.0.0.0/0
      - direction: ingress
        protocol: icmp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 27017
        port_range_min: 27017
        protocol: tcp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 22
        port_range_min: 22
        protocol: tcp
         
  security_group_app:
    type: OS::Neutron::SecurityGroup
    properties:
      description: 'for ICMP,HTTP,SSH'
      name: security-group-app
      rules:
      - direction: egress
        ethertype: IPv4
        remote_ip_prefix: 0.0.0.0/0
      - direction: ingress
        protocol: icmp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 80
        port_range_min: 80
        protocol: tcp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 22
        port_range_min: 22
        protocol: tcp  
