heat_template_version: "2018-08-31"
description: "create template to automation project configuration and start services automatically"

resources:
  network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: auth-app
  network_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      cidr: "192.168.65.0/26"
      dns_nameservers: ["8.8.8.8"]
      gateway_ip: "192.168.65.1"
      ip_version: 4
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }
      name: cloud-app
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: network_subnet }
  port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network }
      fixed_ips:
        - subnet_id: { get_resource: network_subnet }
  port2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: network }
      fixed_ips:
        - subnet_id: { get_resource: network_subnet }
  
